export const projects = [
  {
    title: 'West Coast Creatives',
    description: "Using React & Nextjs, we built a landing page for WCC, a software engineering firm based around the UpWork and aerospace industries.",
      image: '/images/01.png',
      tags: ['Nextjs', 'JavaScript', 'React'],
    source: 'https://westcoastcreatives.net',
    visit: 'https://westcoastcreatives.net',
    id: 0,
  },
  {
    title: 'Petrolnaut Shop',
    description: "Petrolnaut's e-commerce application connected to commerce.js and integration of the Stripe platform for card transactions.",
      image: '/images/02.png',
      tags: [ 'Stripe', 'React', 'JavaScript', 'Nextjs', 'Commercejs'],
    source: 'https://petrolnaut-webstore-v2.netlify.app/',
    visit: 'https://petrolnaut-webstore-v2.netlify.app/',
    id: 1,
  },
  {
    title: 'Mahulani Cafe',
    description: "Basic instagram clone",
      image: '/images/03.png',
      tags: ['React', 'OAuth'],
    source: 'https://mahulanicafe.netlify.app/posts',
    visit: 'https://mahulanicafe.netlify.app/posts',
    id: 2,
  },
  {
    title: 'iWardrobe',
    description: "We built a store front for iWardrobe, one of the leading internet clothing providers.",
    image: '/images/04.png',
    tags: ['React', 'Shopify', 'Nextjs'],
    source: 'https://iwardrobe.netlify.app/',
    visit: 'https://iwardrobe.netlify.app/',
    id: 3,
  },
  {
    title: 'Petrolnaut Racing',
    description: "Go zoom zoom",
    image: '/images/05.png',
    tags: ['React', 'Shopify', 'Nextjs'],
    source: 'https://mattoattacko.github.io/Petrolnaut/',
    visit: 'https://mattoattacko.github.io/Petrolnaut/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Graduated from the University of Hawaii w/ a B.S in Kinesiology and Rehabilitation Science', },
  { year: 2016, text: 'Worked as a strength and conditioning specialist at a physical therapy clinic in Bellevue, Wa', },
  { year: 2017, text: 'Pivoted from the medical field to software development', },
  { year: 2020, text: 'Freelancing on UpWork', },
  { year: 2021, text: 'Founded West Coast Creatives', },
];