export const projects = [
  {
    title: 'West Coast Creatives',
    description: "Landing page for West Coast Creatives LLC, a software development firm based around the UpWork contracting ecosystem.",
    image: "./images/WCCDesktop01.png",
    tags: ['Next.js', 'React', 'Theme UI'],
    source: 'https://westcoastcreatives.net',
    visit: 'https://westcoastcreatives.net',
    id: 0,
  },
  {
    title: 'Moon Miners Association',
    description: "Have you ever wanted to travel to space? So have I! Let's learn more about the in's-&-out's of what it might take to get there, as well as who's been up there. Produced in collaboration with Kevin Powell.",
    image: './images/MoonMinersDesktop.png',
    tags: ['JavaScript', 'Netlify', 'Pure CSS'],
    source: 'https://moonminersassociation.com/',
    visit: 'https://moonminersassociation.com/',
    id: 1,
  },
  {
    title: 'Krypto',
    description: "Cryptocurrency wallet interface utilizing the Ethereum blockchain. Users can send and receive currency via the MetaMask browser extension.",
    image: './images/KryptoDesktop01.png',
    tags: ['HardHat', 'React', 'MetaMask', 'TailwindCSS'],
    source: 'https://kryptojsm.netlify.app/',
    visit: 'https://kryptojsm.netlify.app/',
    id: 2,
  },
  {
    title: 'Easy Bank',
    description: "Landing page for easybank, a next generation digital banking platform. Users can create create budgets, invest, and more through easybank's online financial services.",
    image: './images/EasyBankDesktop01.png',
    tags: ['JavaScript', 'SCSS', 'Netlify'],
    source: 'https://easypaybank.netlify.app/',
    visit: 'https://easypaybank.netlify.app/',
    id: 3,
  },
  {
    title: 'Binary Creatives Network',
    description: "Social media platform for the creative community. Users can create and share content, as well as follow other users creations.",
    image: './images/BinaryDesktop01.png',
    tags: ['Sanity.io', 'React', 'Masonry', 'TailwindCSS'],
    source: 'https://binarycreativesnetwork.netlify.app/',
    visit: 'https://binarycreativesnetwork.netlify.app/',
    id: 4,
  },
  {
    title: 'GPT-3',
    description: "GPT-3, or the third generation Generative Pre-trained Transformer, is a neural network machine learning model trained using internet data to generate any type of text. Developed by OpenAI, it requires a small amount of input text to generate large volumes of relevant and sophisticated machine-generated text.",
    image: './images/GPT3Desktop01.png',
    tags: ['React', 'Netlify', 'Formik'],
    source: 'https://gpt3-wcc.netlify.app/',
    visit: 'https://gpt3-wcc.netlify.app/',
    id: 5,
  },   
  {
    title: 'Gericht',
    description: "Landing page for Gericht, a Japanese-American fusion restaurant that serves up traditional Japanese dishes with a uniquely western spin. Users can view menu items, as well as order food online.",
    image: './images/GerichtDesktop01.png',
    tags: ['React', 'BEM CSS', 'Netlify'],
    source: 'https://gericht-renton.netlify.app/',
    visit: 'https://gericht-renton.netlify.app/',
    id: 6,
  },

  {
    title: 'Sekushi House',
    description: "Dubai-based real estate agency search application that allows users to search for properties in their area. Users can view property details, as well as contact the listing owner.",
    image: './images/SekushiDesktop.png',
    tags: ['React', 'NextJS', 'ChakraUI', 'Vercel'],
    source: 'https://www.sekushi-house.vercel.app',
    visit: 'https://www.sekushi-house.vercel.app',
    id: 7,
  },
  {
    title: 'Petrolnaut Labs',
    description: "Petrolnaut Labs is a video conference platform that allows users to connect with other members of the Petrolnaut racing community in real time. Users can create and join video conferences, as well as chat with other users.",
    image: './images/petrolnautLabsDesktop01.png',
    tags: ['Agora', 'React', 'Apollo', 'Netlify'],
    source: 'https://petrolnautlabs.netlify.app/',
    visit: 'https://petrolnautlabs.netlify.app/',
    id: 8,
  },
 
];

export const TimeLineData = [
  { year: 2015, text: 'University of Hawaii, B.S in Kinesiology and Rehabilitation Science', },
  { year: 2016, text: 'Strength and conditioning specialist with Peak Sports & Spine Physical Therapy. Freelancing on the side.', },
  { year: 2017, text: 'Pivoted from medicine towards fulltime software development.', },
  { year: 2019, text: 'Private contracting via UpWork', },
  { year: 2021, text: 'Co-Founded West Coast Creatives, LLC.', },
];


